import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.page}>
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js logo"
            width={100}
            height={20}
          />

          <div className={styles.intro}>
            <h1>To get started, edit index.js file.</h1>

            <p>
              Looking for a starting point? Visit{" "}
              <a
                href="https://nextjs.org/learn"
                target="_blank"
                rel="noopener noreferrer"
              >
                Next.js Learning
              </a>
            </p>
          </div>

          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="https://vercel.com/new"
              target="_blank"
              rel="noopener noreferrer"
            >
              Deploy Now
            </a>

            <a
              className={styles.secondary}
              href="https://nextjs.org/docs"
              target="_blank"
              rel="noopener noreferrer"
            >
              Documentation
            </a>
          </div>
        </main>
      </div>
    </>
  );
}